[env]
FREERTOS_KERNEL_ROOT_DIR = "${PWD}/freertos/FreeRTOS/FreeRTOS"
FREERTOS_KERNEL_SOURCE_DIR = "${FREERTOS_KERNEL_ROOT_DIR}/Source"
FREERTOS_KERNEL_PORTABLE_DIR = "${FREERTOS_KERNEL_SOURCE_DIR}/portable"
FREERTOS_KERNEL_INCLUDE_DIR = "${FREERTOS_KERNEL_SOURCE_DIR}/include"

[tasks.prebuild]
script_runner = "@shell"
script = '''
cd ./freertos/build
make
'''